### ISSUE TITLE
flate is not found in node

### ISSUE THREAD

**Issue by ghost** [drbh/wasm-flate#15]
Flate is not found although I just installed it? What am I missing?

Any help is much appreciated. Thanks!

```
23:35:07-jonas~/git/gizur/gizur-stats/node-pgnm (master)$ node --version
v12.16.1
23:35:58-jonas~/git/gizur/gizur-stats/node-pgnm (master)$ rm -rf node_modules
23:36:05-jonas~/git/gizur/gizur-stats/node-pgnm (master)$ npm i wasm-flate
npm WARN saveError ENOENT: no such file or directory, open '/Users/jonas/git/gizur/gizur-stats/node-pgnm/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/jonas/git/gizur/gizur-stats/node-pgnm/package.json'
npm WARN node-pgnm No description
npm WARN node-pgnm No repository field.
npm WARN node-pgnm No README data
npm WARN node-pgnm No license field.

+ wasm-flate@1.0.2-browser
added 1 package and audited 1 package in 1.073s
found 0 vulnerabilities

23:36:17-jonas~/git/gizur/gizur-stats/node-pgnm (master)$ node
Welcome to Node.js v12.16.1.
Type ".help" for more information.
> var flate = require('wasm-flate');
Uncaught Error: Cannot find module 'wasm-flate'
Require stack:
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '<repl>' ]
}
> 
```

**Comment by cmdcolin** [comment]
Possibly installing wasm-flate@1.0.2 explicitly as the 1.0.2-browser is otherwise installed
